// API
export const REQUEST_ALL_GREEKS = 'REQUEST_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS = 'RECEIVE_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS_FAILURE = 'RECEIVE_ALL_GREEKS_FAILURE';

// Books
export const REQUEST_BOOKS = 'REQUEST_BOOKS';
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';
export const RECEIVE_BOOKS_FAILURE = 'RECEIVE_BOOKS_FAILURE';

// Quotes
export const REQUEST_QUOTES = 'REQUEST_QUOTES';
export const RECEIVE_QUOTES = 'RECEIVE_QUOTES';
export const RECEIVE_QUOTES_FAILURE = 'RECEIVE_QUOTES_FAILURE';
export const REQUEST_RANDOM_QUOTE = 'REQUEST_RANDOM_QUOTE';
export const RECEIVE_RANDOM_QUOTE = 'RECEIVE_RANDOM_QUOTE';
export const RECEIVE_RANDOM_QUOTE_FAILURE = 'RECEIVE_RANDOM_QUOTE_FAILURE';
export const REQUEST_UPDATE_QUOTES_LIKES = 'REQUEST_UPDATE_QUOTES_LIKES';
export const UPDATE_QUOTE_LIKES_FAILURE = 'UPDATE_QUOTE_LIKES_FAILURE';
export const UPDATE_QUOTE_LIKES = 'UPDATE_QUOTE_LIKES';

